TN/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TN.DAL;
using TN.Models;
using TN.Models.Extended;
using PagedList;
using TN.BLL;

namespace TeklifinNedir.Controllers
{
    public class UrunController : Controller
    {

        TeklifContext db = new TeklifContext();
        GenericRepository<Urunler> urn = new GenericRepository<Urunler>(new TeklifContext());


     
        public ActionResult Index(int Page = 1)
        {
            var lst = db.Urunlers.Where(m => m.Yayın == true).OrderByDescending(m => m.UrunId).ToPagedList(Page, 15);

            return View(lst);
        }


        public ActionResult Urun1()
        {
            var d = db.Urunlers.Where(x => x.Yayın == true).ToList();
            return View(d);
        }
        public ActionResult Urun2()
        {
            Random rnd = new Random();
            int id = rnd.Next(1, 10);
            if (db.Resimlers.Where(m => m.Urunlers.KategoriId == id).ToList() != null)
            {
                var d = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).ToList();
                return View(d);
            }

            var d2 = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).ToList();
            return View(d2);
        }
        public ActionResult Urun3()
        {
            Random rnd = new Random();
            int id = rnd.Next(1, 10);
            if (db.Resimlers.Where(m => m.Urunlers.KategoriId == id).ToList() != null)
            {
                var d = db.Urunlers.Where(m => m.KategoriId == id &&m.Yayın==true).ToList();
                return View(d);
            }

            var d2 = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).ToList();
            return View(d2);
        }
        public ActionResult Urun4()
        {
            Random rnd = new Random();
            int id = rnd.Next(1, 10);
            if (db.Resimlers.Where(m => m.Urunlers.KategoriId == id).ToList() != null)
            {
                var d = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).ToList();
                return View(d);
            }

            var d2 = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).ToList();
            return View(d2);
        }

        [Route("Kategoriler/@={id}/{Page=1}")]
        public ActionResult KatGore(int id, int Page = 1)
        {
            var lst = db.Urunlers.Where(m => m.KategoriId == id && m.Yayın==true).OrderByDescending(m => m.UrunId).ToPagedList(Page, 15);
            

            return View(lst);
        }

        public ActionResult EnCokBakilanlar()
        {
            return View(urn.Listele().Where(x => x.Yayın == true).OrderByDescending(z => z.Bakilma).Take(5));
        }


        public ActionResult Kategoriler()
        {

            TumEkranlar lst = new TumEkranlar();
            lst.Kategorilers = db.Kategorilers.ToList();
            lst.Urunlers = db.Urunlers.Where(x => x.Yayın == true).ToList();

            return View(lst);
        }


        [Route("Urunler/Urun/@={id}/Detay")]
        public ActionResult UrunDetay(int id)
        {
            AnaSayfa a = new AnaSayfa();
            a.Resimlers = db.Resimlers.Where(x => x.UrunId == id).ToList();
            a.Urunler = db.Urunlers.Where(x => x.UrunId == id).Single();
            int c = a.Urunler.UserID;
            a.Iletisim = db.Iletisims.Where(x => x.UserID == c).Single();
            int il = a.Iletisim.IlId;
            int ilce = a.Iletisim.ID;
            a.Il = db.Il.Where(x => x.IlId == il).Single();
            a.Ilce = db.Ilce.Where(x => x.ID == ilce).Single();
            Urunler urun = urn.Bring(id);
            urun.Bakilma += 1;
            urn.Edit(urun);
            return View(a);
        }

        public ActionResult Detay(int id)
        {
            return View(db.Resimlers.Where(m => m.UrunId == id).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
                urn.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

TN/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TN.DAL;
using TN.Models;
using System.ComponentModel.DataAnnotations;
using TN.Models.Extended;
using System.Web.Security;
using System.Net.Mail;
using System.Net;
using TN.BLL;

namespace TeklifinNedir.Controllers
{
    public class UserController : Controller
    {
        TeklifContext dc = new TeklifContext();
        GenericRepository<User> dg = new GenericRepository<User>(new TeklifContext());
        GenericRepository<Iletisim> ilet = new GenericRepository<Iletisim>(new TeklifContext());

        [Authorize]
        public ActionResult Index()
        {

            return View();
        }

        //Registration Action
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }
        //Registration POST action 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration([Bind(Exclude = "IsEmailVerified,ActivationCode")]User1 user)
        {
            bool Status = false;
            string message = "";

            if (ModelState.IsValid)
            {


                #region //Email is already Exist 
                var isExist = IsEmailExist(user.EmailID);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "E-posta zaten var");
                    return View(user);
                }
                #endregion
                #region Generate Activation Code 
                user.ActivationCode = Guid.NewGuid();
                #endregion

                #region  Password Hashing 
                user.Password = Crypto.Hash(user.Password);
                user.ConfirmPassword = Crypto.Hash(user.ConfirmPassword); //
                #endregion
                user.IsEmailVerified = false;
                #region Save to Database
                using (TeklifContext dc = new TeklifContext())
                {
                    user.UyelikBaslangic = DateTime.Now;
                    dc.Users.Add(user);
                    dc.SaveChanges();
                    Session["user"] = user;
                    //Send Email to User
                    SendVerificationLinkEmail(user.EmailID, user.ActivationCode.ToString());
                    message = "Kayıt işleminizi yarıladınız :) Hesap etkinleştirme " +
                        " bağlantısı email adresinize gönderildi:" + user.EmailID;
                    Status = true;
                }
                #endregion
            }
            else
            {
                message = "Geçersiz istek";
            }


            // Model Validation 


            ViewBag.Message = message;
            ViewBag.Status = Status;

            return View(user);
        }
        //Verify Account  
        public ActionResult Iletisim()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Iletisim(FormCollection c)
        {
            if (ModelState.IsValid)
            {
                Iletisim ileti = new Iletisim();
                ileti.IlId = Convert.ToInt32(c["il"]);
                ileti.ID = Convert.ToInt32(c["ilce"]);
                ileti.Adres = c["Adres"].ToString();
                ileti.Tel = c["Tel"].ToString();
                ileti.UserID = ((User)Session["user"]).UserID;
                TempData["msg"] = ilet.Create(ileti) ? "İletişim Bilgileriniz Kaydedildi.." : "Hata ! Lütfen Tekrar Deneyiniz...";
                return RedirectToAction("Index", "Kullanici");

            }

            return View();
        }

        [HttpPost]
        public JsonResult IlIlce(int? ilId, string tip)
        {
            //EntityFramework ile veritabanı modelimizi oluşturduk ve
            //IlilceDBEntities ile db nesnesi oluşturduk.

            //geriye döndüreceğim sonucListim
            List<SelectListItem> sonuc = new List<SelectListItem>();
            //bu işlem başarılı bir şekilde gerçekleşti mi onun kontrolunnü yapıyorum
            bool basariliMi = true;
            try
            {
                switch (tip)
                {
                    case "ilGetir":
                        //veritabanımızdaki iller tablomuzdan illerimizi sonuc değişkenimze atıyoruz
                        foreach (var il in dc.Il.ToList())
                        {
                            sonuc.Add(new SelectListItem
                            {
                                Text = il.Ad,
                                Value = il.IlId.ToString()
                            });
                        }
                        break;
                    case "ilceGetir":
                        //ilcelerimizi getireceğiz ilimizi selecten seçilen ilID sine göre 
                        foreach (var ilce in dc.Ilce.Where(il => il.IlId == ilId).ToList())
                        {
                            sonuc.Add(new SelectListItem
                            {
                                Text = ilce.Ad,
                                Value = ilce.ID.ToString()
                            });
                        }
                        break;

                    default:
                        break;

                }
            }
            catch (Exception)
            {
                //hata ile karşılaşırsak buraya düşüyor
                basariliMi = false;
                sonuc = new List<SelectListItem>();
                sonuc.Add(new SelectListItem
                {
                    Text = "Bir hata oluştu :(",
                    Value = "Default"
                });

            }
            //Oluşturduğum sonucları json olarak geriye gönderiyorum
            return Json(new { ok = basariliMi, text = sonuc });
        }

        [HttpGet]
        public ActionResult VerifyAccount(string id)
        {
            bool Status = false;
            using (TeklifContext dc = new TeklifContext())
            {
                dc.Configuration.ValidateOnSaveEnabled = false; // This line I have added here to avoid 
                                                                // Confirm password does not match issue on save changes
                var v = dc.Users.Where(a => a.ActivationCode == new Guid(id)).FirstOrDefault();
                if (v != null)
                {
                    v.IsEmailVerified = true;
                    dc.SaveChanges();
                    Status = true;
                }
                else
                {
                    ViewBag.Message = "Geçersiz istek";
                }
            }
            ViewBag.Status = Status;
            return View();

        }

        //Login 
        [HttpGet]
        public ActionResult Login()
        {

            return View();

        }

        //Login POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserLogin login, User u, string ReturnUrl = "")
        {
            string message = "";
            using (TeklifContext dc = new TeklifContext())
            {
                var v = dc.Users.Where(a => a.EmailID == login.EmailID).FirstOrDefault();
                if (v != null)
                {
                    if (!v.IsEmailVerified)
                    {
                        ViewBag.Message = "Lütfen önce email adresinizi doğrulayın..";
                        return View();
                    }

                    if (string.Compare(Crypto.Hash(login.Password), v.Password) == 0)
                    {
                        if (login.RememberMe == true)
                        {
                            HttpCookie cerezz = new HttpCookie("cerezim");
                            cerezz.Values.Add("Email", u.EmailID);
                            cerezz.Values.Add("Password", login.Password);
                            cerezz.Expires = DateTime.Now.AddDays(30);
                            Response.Cookies.Add(cerezz);
                        }
                        int timeout = login.RememberMe ? 525600 : 20; // 525600 min = 1 year
                        var ticket = new FormsAuthenticationTicket(login.EmailID, login.RememberMe, timeout);
                        string encrypted = FormsAuthentication.Encrypt(ticket);
                        var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                        cookie.Expires = DateTime.Now.AddMinutes(timeout);
                        cookie.HttpOnly = true;


                        Response.Cookies.Add(cookie);


                        if (Url.IsLocalUrl(ReturnUrl))
                        {

                            return Redirect(ReturnUrl);
                        }
                        else
                        {

                            var c = dc.Users.Where(p => p.EmailID == u.EmailID).FirstOrDefault();
                            Session["user"] = c;
                            return RedirectToAction("UrunIndex", "Kullanici");
                        }
                    }
                    else
                    {
                        message = "Geçersiz kimlik bilgisi..";
                    }
                }
                else
                {
                    message = "Geçersiz kimlik bilgisi..";
                }
            }
            ViewBag.Message = message;
            return View();
        }

        //Logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            Session["user"] = null;
            Session["teksay"] = null;
            Session["msjsay"] = null;
            Session["kimeid"] = null;
            Session["urunid"] = null;
            HttpContext.User = null;
            if (Request.Cookies["cerezim"] != null)
            {
                Response.Cookies["cerezim"].Expires = DateTime.Now.AddDays(-1);

TN/Views/Home/AcikArtirma.cshtml
<div id="hot-deal" class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hot-deal">
                    <ul class="hot-deal-countdown" id="timer">
                        <li>
                            <div>
                                <h3 id="timer-gunler"></h3>

                            </div>
                        </li>
                        <li>
                            <div>
                                <h3 id="timer-saatler"></h3>

                            </div>
                        </li>
                        <li>
                            <div>
                                <h3 id="timer-dakikalar"></h3>

                            </div>
                        </li>
                        <li>
                            <div>
                                <h3 id="timer-saniyeler"></h3>

                            </div>
                        </li>
                    </ul>
                    <h2 class="text-uppercase">Yakın zamanda burada !!</h2>
                    <p>
                        <h5>
                            Belirlenen Süre İçerisin de Ürünlerinizi burada satabilir
                            <br />
                            / Teklif verip alabilirsiniz !!
                        </h5>
                    </p>

                    <p style="color:#ebf500"><h1>Teklifin Nedir</h1></p>
                    <a class="primary-btn cta-btn" href="#">Haydi Teklif Ver</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var endDate = new Date("June 01, 2020 00:00:00").getTime();
    var timer = setInterval(function () {

        let now = new Date().getTime();
        let t = endDate - now;

        if (t >= 0) {

            let gunler = Math.floor(t / (1000 * 60 * 60 * 24));
            let saatler = Math.floor((t % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            let dakikalar = Math.floor((t % (1000 * 60 * 60)) / (1000 * 60));
            let saniyeler = Math.floor((t % (1000 * 60)) / 1000);

            document.getElementById("timer-gunler").innerHTML = gunler +
                "<span class='label'> gün</span>";

            document.getElementById("timer-saatler").innerHTML = ("0" + saatler).slice(-2) +
                "<span class='label'> sa</span>";

            document.getElementById("timer-dakikalar").innerHTML = ("0" + dakikalar).slice(-2) +
                "<span class='label'> dk</span>";

            document.getElementById("timer-saniyeler").innerHTML = ("0" + saniyeler).slice(-2) +
                "<span class='label'> sn</span>";
        }
        else {
            document.getElementById("timer").innerHTML = "Zaman bitti!";
        }


    }, 1000);
</script>

TN/Views/Home/Detay.cshtml
@model TN.Models.Extended.AnaSayfa
@{
    ViewBag.Title = "Detay";
   Layout = "~/Views/Shared/_LayoutKul.cshtml";
}


@Html.Action("HeaderDesktop", "Home")
@Html.Action("HeaderMobile", "Home")


<div class="page-content--bgf7">
    <div class="main-content">
        <div class="section__content--p35">
            <div class="container-fluid">
                <div id="aside" class="col-md-2">
                    @Html.Action("Kategoriler", "Urun")

                    @Html.Action("EnCokBakilanlar", "Urun")
                </div>
                <div class="row">
                    <div class="col-md-4" id="slider">
                        <div class="row">
                            <div class="span5" id="carousel-bounding-box">
                                <div class="carousel slide" id="myCarousel">
                                    <a class="carousel-control left" data-slide="prev" href="#myCarousel">‹</a> <a class="carousel-control right" data-slide="next" href="#myCarousel">›</a>
                                    <div class="carousel-inner">
                                        @{ int i = 0;}
                                        @{ int l = 0;}
                                        @foreach (var item in Model.Resimlers)
                                        {
                                            i++;
                                            l++;
                                            var active = i == 1 ? "active" : "";
                                        <div class="@active item" data-slide-number="@l">
                                            <a href="@item.ImageUrl" data-lightbox="@item.ImageUrl"><img src="@item.ImageUrl"></a>
                                        </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6" >
                        <div class="col-12 text-center">  <h3>@Html.DisplayFor(m => m.Urunler.Baslik)</h3></div>
                        <div class="col-12 text-right"> <h6>@Html.DisplayFor(m => m.Il.Ad) / @Html.DisplayFor(m => m.Ilce.Ad)</h6></div>
                        <div class="col-12 table-responsive" style="background-color:rgba(232, 251, 67, 0.11)">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td class="a">İlan Veren</td>
                                        <td class="text-right"> @Html.DisplayFor(m => m.Urunler.User.FirstName)</td>
                                    </tr>
                                    <tr>
                                        <td class="a">İlan No</td>
                                        <td class="text-right"> @Html.DisplayFor(m => m.Urunler.UrunId)</td>
                                    </tr>

                                    <tr>
                                        <td class="a">Kategori</td>
                                        <td class="text-right"> @Html.DisplayFor(m => m.Urunler.Kategoriler.KategoriAdi)</td>
                                    </tr>
                                    <tr>
                                        <td class="a"></td>
                                        <td class="text-right">@Html.DisplayFor(m => m.Urunler.Aciklama)</td>
                                    </tr>
                                    <tr>
                                        <td class="a">Durumu</td>
                                        <td class="text-right"> @Html.DisplayFor(m => m.Urunler.Durum.Durumu)</td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                        <div class="fc-button-group" style="margin-top:15px">
                            <div class="col-md-3" style="float:right">
                                <div class="row">
                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".bd-example-modal-sm" id="BtnUye" style="margin-top:5px">
                                        <i class="fa fa-try"></i> TeklifVer
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-3" style="float:left">
                                <div class="row">
                                    <button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#exampleModal" id="Btn2" style="margin-top:5px;margin-right:10px"><i class="fa fa-send"></i> Ürün Hakkında Soru Sorabilirsin !!</button>
                                    <div style="margin-top:5px;margin-top:5px"><a class="btn btn-xs btn-default" href="@Url.Action("Index", "Home")">Geri Dön</a></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-8" style="margin-top:5px">
                        <div class="row hidden-phone">
                            @{int g = 0;}
                            @foreach (var item in Model.Resimlers)
                            {
                                int k = g++;
                            <div class="col-sm-1" style="margin-right:20px">
                                <a class="thumbnail" id="carousel-selector-@k" style="width:70px;height:70px">  <img src="@item.ImageUrl" style="width:50px;height:50px" />    </a> 
                                </div>
                            }
                     
                        </div>
                    </div>
                </div>
            </div>

            <div class="section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Action("Urun1", "Home")
                        </div>
                        <div class="col-md-3">
                            @Html.Action("Urun2", "Home")
                        </div>
                        <div class="col-md-3">
                            @Html.Action("Urun3", "Home")
                        </div>
                        <div class="col-md-3">
                            @Html.Action("Urun4", "Home")
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

<script>jQuery(document).ready(function ($) { $('#myCarousel').carousel({ interval: 3000 }); $('#carousel-text').html($('#slide-content-0').html()); $('[id^=carousel-selector-]').click(function () { var id_selector = $(this).attr("id"); var id = id_selector.substr(id_selector.length - 1); var id = parseInt(id); $('#myCarousel').carousel(id); }); $('#myCarousel').on('slid', function (e) { var id = $('.item.active').data('slide-number'); $('#carousel-text').html($('#slide-content-' + id).html()); }); });</script>
@section Scripts{

    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true
        })
    </script>

}

TN/Views/Home/Footer.cshtml
@model TN.Models.Extended.TumEkranlar
<footer id="footer" style="padding-top:40px;">
  
    <div class="section">
    
        <div class="container">
           
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h6 class="title" style="color:#808080">Girişler</h6>
                        <ul class="footer-links">
                            <li><a href="@Url.Action("Login","User")"><i class="fa fa-user"></i>Giriş Yap</a></li>
                            <li><a href="@Url.Action("Registration","User")"><i class="fa fa-user-plus"></i>Üye Ol</a></li>
                            <li><a href="@Url.Action("UrunEkle","Post")"><i class="fa fa-file-image-o"></i>İlan Ver</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h6 class="title" style="color:#808080">Kategoriler</h6>
                        <ul class="footer-links">
                            @foreach (var item in Model.Kategorilers)
                            {
                                <li><a href="@Url.Action("KatGore","Urun",new {id=item.KategoriId })">@item.KategoriAdi (@item.Urunler.Where(z => z.KategoriId == item.KategoriId).Count())</a></li>
                            }
                        </ul>
                    </div>
                </div>

                <div class="clearfix visible-xs"></div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h6 class="title" style="color:#808080">Son Yüklenenler</h6>
                        <ul class="footer-links">
                            @foreach (var item in Model.Urunlers)
                            {
                                <li><img src="@item.AnaGorsel.Resimler.ImageUrl" style="width:30px;height:30px" />  <a href="@Url.Action("Detay","Home",new { id=item.UrunId})"> @item.Baslik</a></li>
                            }
                        </ul>
                    </div>
                </div>


                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h6 class="title" style="color:#808080">Bize Ulaşın</h6>
                        <ul class="footer-links">
                            <li><a href="@Url.Action("Index","SartlarKosullar")">Şartlar & Koşullar</a></li>
                            <li><a href="@Url.Action("GizlilikPolitikamiz","SartlarKosullar")">Gizlilik Politikamız</a></li>
                            <li><a href="@Url.Action("Kurallar","SartlarKosullar")">Kurallarımız</a></li>
                            <li><a><i class="fa fa-instagram"></i>teklifinedir</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i>info@teklifinedir.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

TN/Views/Home/HeaderDesktop.cshtml
@using TN.Models
@model IEnumerable<TN.Models.Kategoriler>

<header class="header-desktop3 d-none d-lg-block">
    <div class="section__content section__content--p35">
        <div class="header3-wrap">
            <div class="header__logo">
                <a href="@Url.Action("Index","Home")">
                    <img src="~/Content/img/yazi.png" alt="teklifiNedir">
                </a>
            </div>
            <div class="header__navbar">
                <ul class="list-unstyled">
                    <li class="has-sub">
                        <a href="@Url.Action("Index","Urun")">
                            <i class="fas fa-barcode"></i>Kategoriler
                            <span class="bot-line"></span>
                        </a>
                        <ul class="header3-sub-list list-unstyled">
                            <li><a href="@Url.Action("Index","Urun")">Tüm Kategoriler</a></li>
                            @foreach (var item in Model)
                            {
                                <li>
                                    <a href="@Url.Action("KatGore", "Urun",new {id=item.KategoriId })">@item.KategoriAdi</a>
                                </li>
                            }
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-times"></i>
                            <span class="bot-line"></span>Açık Artırmalar
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("UrunEkle","Post")"><i class="fa fa-photo"></i>İlan Ver</a>
                    </li>
                
                    <li>
                        <a href="@Url.Action("Login", "User")"  style="background-color:#ffd800"> Giriş</a>
                    </li>
                </ul>
            </div>
        
        </div>
    </div>
</header>

TN/Views/Home/HeaderMobile.cshtml
@using TN.Models
@model IEnumerable<TN.Models.Kategoriler>


<header class="header-mobile header-mobile-2 d-block d-lg-none">
    <div class="header-mobile__bar">
        <div class="container-fluid">
            <div class="header-mobile-inner">
                <a class="logo" href="@Url.Action("Index","Home")">
                    <img src="~/Content/img/yazi.png" alt="teklifiNedir">
                </a>
                <button class="hamburger hamburger--slider" type="button">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <nav class="navbar-mobile" style="display: none;">
        <div class="container-fluid">
            <ul class="navbar-mobile__list list-unstyled">
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-barcode"></i>Kategoriler
                    </a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list" style="display: none;">
                        <li>
                            <a href="@Url.Action("Index","Urun")">Tüm Kategoriler</a>
                        </li>
                        @foreach (var item in Model)
                        {
                            <li>
                                <a href="@Url.Action("KatGore","Urun",new { id=item.KategoriId})">@item.KategoriAdi</a>
                            </li>
                        }
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>
<div class="sub-header-mobile-2 d-block d-lg-none">
   
    <a href="@Url.Action("Login", "User")" class="btn btn-success" style="margin:5px"> <i class="fa fa-user"></i> Giriş</a> <a href="@Url.Action("UrunEkle","Post")" class="btn btn-primary" style="margin:5px"> <i class="fa fa-photo"></i> İlan Ver</a>
</div>